### PR TITLE
fix(TouchHandler): Consider all possible views for click target

### LINKED ISSUE #715: react-native-drawer - non-drawer content not interactive
Using react-native-windows 0.33.1 and RN 0.33,
When using [react-native-drawer](https://github.com/root-two/react-native-drawer) the main content (the child) of the `Drawer` compoennt is not interactive. On iOS and Android the same code works fine. No `onPress` event handlers fire for any elements.  Simple example code below:

```typescript
<Drawer
	ref="navigation"
	open={state.open}
	onOpen={() => {setState({open:true});}
	onClose={() => {setState({open:false};}
	type="displace"
	content={<Settings />}
	tapToClose={true}
	openDrawerOffset={0.2}
	panCloseMask={0.2}
	negotiatePan={true}
	tweenHandler={(ratio: number) => ({
		main: { opacity: Math.max(0.54, 1 - ratio) }
	})}>
	<View style={{width:200,height:200, backgroundColor:"red",margin:50}}>
		<Text onPress={()=>console.log("PRESS")}>Text</Text>
	</View>
</Drawer >
```

### PR DESCRIPTION
**Pull request by rozele**
Previously, we were only considering the hierarchy from the pointer "OriginalSource" in the pointer events calculations. Unfortunately, this meant that if a transparent overlay with "box-none" or "none" pointer events was set, as is the case for "react-native-drawer", then no alternative targets would be considered. This change uses VisualTreeHelper.FindElementsInHostCoordinates to consider all possible targets.

Fixes #715

### CODE REVIEW

File: ReactWindows/ReactNative/Touch/TouchHandler.cs [hunk 1]
```diff
@@ -4,8 +4,11 @@
 using ReactNative.UIManager.Events;
 using System;
 using System.Collections.Generic;
+using System.Linq;
```
Comment (rozele) [inline ReactWindows/ReactNative/Touch/TouchHandler.cs]: Not needed.

File: ReactWindows/ReactNative/Touch/TouchHandler.cs [hunk 2]
```diff
@@ -45,8 +48,7 @@ private void OnPointerPressed(object sender, PointerRoutedEventArgs e)
                 throw new InvalidOperationException("A pointer with this ID already exists.");
             }
 
-            var reactView = GetReactViewFromView(e.OriginalSource as UIElement);
-
+            var reactView = GetReactViewFromPoint(e.GetCurrentPoint(_view).Position);
```
Comment (rozele) [inline ReactWindows/ReactNative/Touch/TouchHandler.cs]: Double check if you can re-use this calculated value for the event args.

File: ReactWindows/ReactNative/Touch/TouchHandler.cs [hunk 3]
```diff
@@ -123,31 +125,49 @@ private int IndexOfPointerWithId(uint pointerId)
...
+                    if (parentView == source)
+                    {
+                        continue;
+                    }
+
+                    var isBoxOnly = default(bool);
+                    if (!isBoxOnlyCache.TryGetValue(parentView, out isBoxOnly))
+                    {
+                        pointerEvents = parentView.GetPointerEvents();
+                        isBoxOnly = pointerEvents == PointerEvents.BoxNone || pointerEvents == PointerEvents.None;
```
Comment (rozele) [inline ReactWindows/ReactNative/Touch/TouchHandler.cs]: *BoxOnly

**Comment by rozele** [comment]
Would be good to get another set of eyes on this @mpodwysocki @matthargett @phongcao, touch is a reasonably important aspect of the framework ;-)

**Comment by mpodwysocki** [comment]
LGTM :shipit:

File: ReactWindows/ReactNative/Touch/TouchHandler.cs (hunk 2 above)
Comment (rozele) [inline ReactWindows/ReactNative/Touch/TouchHandler.cs]: #wontfix hopefully the API has some caching.
