### PR TITLE
fix(Image): Add width/height/url to OnLoad event

### LINKED ISSUE #754: Include image dimensions & url in Image's onLoad callback
The Image onLoad event object should match this structure: 

```
{
  source: {
    width: number,
    height: number,
    url: string
}
```

This feature is available on the other React Native platforms:
- [iOS](https://github.com/facebook/react-native/commit/84f68c338a09d6d0dc29985874b54e7d23fcc933)
- [Android](https://github.com/facebook/react-native/pull/9608)

### PR DESCRIPTION
**Pull request by rozele**
Adds expected parameters to event data for image OnLoad event.

Fixes #754

### CODE REVIEW

File: ReactWindows/ReactNative/Views/Image/ReactImageLoadEvent.cs [hunk 1]
```diff
@@ -25,16 +26,46 @@ public class ReactImageLoadEvent : Event
...
+        {
+        }
+
+        /// <summary>
+        /// Instantiates a <see cref="ReactImageLoadEvent"/>.
+        /// </summary>
+        /// <param name="viewId">The view identifier.</param>
+        /// <param name="eventType">The event identifier.</param>
+        /// <param name="imageUri">The image URI.</param>
+        public ReactImageLoadEvent(int viewId, int eventType, string imageUri)
```
Comment (rozele) [inline ReactWindows/ReactNative/Views/Image/ReactImageLoadEvent.cs]: Can probably delete this, doesn't seem to be needed (yet)
