### PR TITLE
fix(TextInput): Enable user padding settings for TextInput.

### LINKED ISSUE #651: Some styles that work for iOS and/or Android have no impact in Win
I believe I saw something about a guide outlining the differences in some style props between platforms.  That would be extremely helpful.  I'm trying to restyle my app now and running into some issues.

So I cloned the example project and was messing around with the styles to ensure other parts of my existing app were not causing conflict. 

For example: On a TextInput I attempted to set a fontSize: 14, padding: 50. Which on iOS would create a very large input area.  I could also set height in iOS.   

On Win, only the fontSize seems to change.  

Am I missing something or are there just going to be standard styles that won't be available in Win yet?

### PR DESCRIPTION
**Pull request by rozele**
Padding settings were not accounted for because of the default paddings set for measurement.

Fixes #651

### CODE REVIEW

File: ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs [hunk 1]
```diff
@@ -1,4 +1,5 @@
-﻿using Facebook.CSSLayout;
+﻿using System;
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs]: Sort.

File: ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs [hunk 2]
```diff
@@ -208,5 +209,18 @@ public void SetShouldNotifyOnLayout(bool shouldNotifyOnLayout)
...
+        /// <param name="padding">The padding value.</param>
+        /// <remarks>
+        /// Override this virtual method if the view has custom padding behavior.
+        /// </remarks>
+        protected virtual void SetPaddingCore(CSSSpacingType spacingType, float padding)
+        {
+            SetPadding(spacingType, padding);
+        }
     }
 }
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/LayoutShadowNode.cs]: newline?

File: ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs [hunk 3]
```diff
@@ -22,7 +21,16 @@ public class ReactTextInputShadowNode : LayoutShadowNode
     {
         private const int Unset = -1;
 
+        private static readonly float[] s_defaultPaddings = new[]
```
Comment (mpodwysocki) [inline ReactWindows/ReactNative/Views/TextInput/ReactTextInputShadowNode.cs]: where did we get these numbers from?  Just from the text input itself with default settings?

**Comment by mpodwysocki** [comment]
LGTM :shipit:

**Comment by kcfgl** [comment]
A few other styles are also missing:

backgroundColor,
borderRadius,
borderColor

**Comment by mpodwysocki** [comment]
@kcfgl if you want to use `borderRadius` use a `View` which is actually a `Border` with a `Canvas` inside it so you can style the `TextBox` accordingly.
