### PR TITLE
fix(CLI): Add better error handling for react-native-windows generator CLI

### LINKED ISSUE #778: react-native windows command fails because there is no react-native-windows version compatible with the latest RN
### Repro Steps

I followed the instructions for Getting Started in the README. After running `react-native windows`, I got this error:

```
Installing react-native-windows@0.35.*...
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "react-native-windows@0.35.*"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! No compatible version found: react-native-windows@0.35.*
npm ERR! Valid install targets:
npm ERR! 1.0.0, 0.35.0-rc.0, 0.34.1, 0.34.0, 0.34.0-rc.0, 0.33.4, 0.33.3, 0.33.1, 0.33.0-rc.1, 0.33.0-rc.0, 0.32.1, 0.32.0, 0.32.0-rc.0, 0.31.3, 0.31.2, 0.31.1, 0.31.0, 0.31.0-rc.1, 0.31.0-rc.0, 0.30.0, 0.30.0-rc.0, 0.29.2, 0.29.1, 0.29.0, 0.29.0-rc.0, 0.28.3, 0.28.2, 0.28.1, 0.28.0, 0.28.0-rc.1, 0.28.0-rc.0, 0.27.0, 0.27.0-rc, 0.2.5-rc7, 0.2.4, 0.2.3, 0.2.2, 0.2.1, 0.1.0
```

### Cause

I have `react-native` version `0.35.0` installed. I guess this is erroring because it's trying to install `react-native-windows` version `0.35.*` but this version pattern isn't compatible with any of the available `react-native-windows` versions based on the rules of semantic versioning.

### Work Around

Developers can work around this issue by running this command:

```
react-native windows --windowsVersion 0.35.0-rc.0
```

### PR DESCRIPTION
**Pull request by rozele**
Previously, when a version of react-native-windows that matched react-native was not available, a somewhat cryptic dump of all available react-native-windows versions was displayed.  Now, we give a specific message suggesting the version could not be found, what the latest version of react-native-windows is, and a suggestion to upgrade/downgrade to the react-native version that matches.

Fixes #778

### CODE REVIEW

File: local-cli/rnpm/windows/src/windows.js [hunk 1]
```diff
@@ -34,6 +35,27 @@ const REACT_NATIVE_PACKAGE_JSON_PATH = function() {
   );
 };
 
+function getLatestPackage() {
```
Comment (rozele) [inline local-cli/rnpm/windows/src/windows.js]: Call this getLatestVersion and update behavior with additional `then`
