### PR TITLE
fix(TextInput): Perform more accurate measurement for PasswordBox

### LINKED ISSUE #855: Using secureTextEntry on TextInput shifts down input on UWP.
I've been having trouble with the secureTextEntry. When I use it on my text input it gets shifted down a notch like shown here:

### Not using secureTextEntry

Without secureTextEntry

### Using secureTextEntry

With secureTextEntry

### Example

Down here is an example written in typescript, that shows the issue.

```javascript
import * as React from "react";
import { View, StyleSheet, TextInput } from "react-native";

export default () => {
    return (
        <View style={styles.containerStyle}>
            <TextInput
                style={styles.inputStyle}
                placeholder={"Enter your password"}
                secureTextEntry
                />
        </View>
    );
};

const styles = StyleSheet.create({
    inputStyle: {
        fontSize: 18,
        lineHeight: 23,
        flex: 1
    } as React.TextStyle,
    containerStyle: {
        height: 40,
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#000"
    } as React.TextStyle,
});
```
I've use the inspector to try and find out where the extra spacing is comming from but I couldn't find any abnormalities.

Is this a bug or am I missing something?

### PR DESCRIPTION
**Pull request by rozele**
`PasswordBox.Measure(size)` does not result in a value being set for `PasswordBox.DesiredSize` property. The same goes for `TextBox`, which we worked around by measuring a `TextBlock` and including the `TextBox` margin values in the resulting measurement. Making the same change for `PasswordBox`.

Fixes #855

### CODE REVIEW

File: ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxShadowNode.cs [hunk 1]
```diff
@@ -222,18 +227,25 @@ private static MeasureOutput MeasureTextInput(CSSNode node, float width, CSSMeas
                 var textNode = (ReactPasswordBoxShadowNode)node;
 
                 var passwordBox = new PasswordBox();
```
Comment (rozele) [inline ReactWindows/ReactNative/Views/TextInput/ReactPasswordBoxShadowNode.cs]: Delete
