### PR TITLE
fix(TouchHandler): Add support to pointerEvents

### LINKED ISSUE #484: Fix Pointer Events Example
There are various Pointer Events examples where the user sets, e.g., "box-none" or "box-only" and it affects the propagation of pointer events.  We need to investigate how to create the right behaviors here.

Take a look at the Android or iOS UIExplorer to see the desired behavior.

### PR DESCRIPTION
**Pull request by ebragge**
Fixes #484

### CODE REVIEW

**Comment by rozele** [comment]
I was looking through the Android code, and it looks like in Android they use a top-down approach from the root view to determine the target tag.  Windows won't support anything like that (the deepest view is usually the touch target). We may need to enumerate the parents from the root and evaluate in the same way Android evaluates (top-down).

Instead of threading the value through the shadow node and affecting the public surface of UIManager, I would suggest we create an interface like ReactPointerEventsView from Android and make ReactViewManager return ReactCanvas, which will be a Canvas that implements this interface.  That way we can use a TypeAs check as we walk the set of FrameworkElements.

File: ReactWindows/ReactNative/Views/View/ReactViewManager.cs [hunk 1]
```diff
@@ -21,13 +22,41 @@ public override string Name
...
+        /// Set the pointer events handling mode for the view.
+        /// </summary>
+        /// <param name="view">The view.</param>
+        /// <param name="pointerEvents">The pointerEvents mode.</param>
+        [ReactProp(ViewProps.PointerEvents)]
+        public void SetPointerEvents(Border view, string pointerEvents)
+        {
+            var inner = GetInnerElement(view);
+
+            if (pointerEvents.Equals("none"))
```
Comment (rozele) [inline ReactWindows/ReactNative/Views/View/ReactViewManager.cs]: Use EnumHelpers.
