### PR TITLE
fix(BundleLoader) - use file locations instead of loading scripts directly

### LINKED ISSUE #644: Script Loader - Implement loading from file instead of script source
Let the underlying `IJavaScriptExecutor` load the file from source instead of loading the script entirely in the Script Loader.

### PR DESCRIPTION
**Pull request by mpodwysocki**
Closes #644

### CODE REVIEW

File: ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs [hunk 1]
```diff
@@ -108,7 +104,7 @@ public override void LoadScript(IReactBridge bridge)
                 }
 
                 bridge.RunScript(_script, SourceUrl);
-                
+
                 _script = null;
```
Comment (rozele) [inline ReactWindows/ReactNative/Bridge/JavaScriptBundleLoader.cs]: You can delete this last part nulling out the string, it was only done to try and get the JavaScript garbage collected (the paths will be quite small anyway)

File: ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs [hunk 2]
```diff
@@ -112,10 +114,26 @@ public void RunScript(string script, string sourceUrl)
             if (sourceUrl == null)
                 throw new ArgumentNullException(nameof(sourceUrl));
 
+            string source = null;
+            try
```
Comment (rozele) [inline ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs]: Can we put all this in an async helper method and

File: ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs [hunk 3]
```diff
@@ -112,10 +114,26 @@ public void RunScript(string script, string sourceUrl)
...
+            {
+                var storageFile = StorageFile.GetFileFromPathAsync(script).AsTask().Result;
```
Comment (rozele) [inline ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs]: Can we put all this in an async helper method and only block on that?

**Comment by rozele** [comment]
Other than the two comments, LGTM.  I don't like the idea of blocking the JavaScript thread, but there's no other option.

File: ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs [hunk 4]
```diff
@@ -126,6 +131,24 @@ public void RunScript(string script, string sourceUrl)
             }
         }
 
+        private async Task<string> LoadScript(string file)
```
Comment (rozele) [inline ReactWindows/ReactNative/Chakra/Executor/ChakraJavaScriptExecutor.cs]: private static and Async suffix.

**Comment by rozele** [comment]
:shipit:
