### PR TITLE
fix(Clipboard) - add interface/facade for testability

### LINKED ISSUE #262: ClipboardModule unit tests crash test execution process
When you "run all" the clipboard module unit tests will result in the app crashing.  Please ping @rozele if you cannot repro or need a crash dump.

The issue seems to have to do with access to the dispatcher thread.

### PR DESCRIPTION
**Pull request by mpodwysocki**
Creates a testable Clipboard module which will help close #262

### CODE REVIEW

File: ReactWindows/ReactNative/Modules/Clipboard/IClipboardInstance.cs [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+        /// <summary>
+        /// Removes all data from the Clipboard.
+        /// </summary>
+        void Clear();
+
+        /// <summary>
+        /// Gets the current content that is stored in the clipboard object.
+        /// </summary>
+        /// <returns>Contains the content of the Clipboard.</returns>
+        DataPackageView GetContent();
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Clipboard/IClipboardInstance.cs]: You're probably already aware of this but DataPackageView is sealed with an internal constructor, while will make it quite difficult to mock.

Comment (mpodwysocki) [inline ReactWindows/ReactNative/Modules/Clipboard/IClipboardInstance.cs]: @rozele actually, it's not that hard because you can create the `DataPackage` which will give you your view:
```cs
var package = new DataTransfer.DataPackage();
package.SetData(DataTransfer.StandardDataFormats.Text, text);
var view = package.GetView();
```

**Comment by rozele** [comment]
:shipit:
