### PR TITLE
fix(AsyncStorage): ensure getAllKeys from filenames are translated

### LINKED ISSUE #724: AsyncStorage returns wrong keys
Using redux-persist with AsyncStorage, data is stored as reduxPersist:reducer. The AsyncStorageModule replaces the colon with {col} to store the data, but when getAllKeys is called, the {col} is not substituted with the colon, which causes redux-persist to fail rehydrating the store.

### PR DESCRIPTION
**Pull request by rozele**
The mapping used from key to filename was not used to convert from filename back to key. Additionally, adds some optimizations to reduce allocations for AsyncStorage.

Fixes #724

### CODE REVIEW

**Comment by rozele** [comment]
cc @Cacowned

File: ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs [hunk 1]
```diff
@@ -327,78 +348,121 @@ public void OnDestroy()
...
+        {
+            var length = fileName.Length - FileExtension.Length;
+            var sb = default(StringBuilder);
+            for (var i = 0; i < length; ++i)
+            {
+                var start = fileName[i];
+                if (start == '{')
+                {
+                    var j = i;
+                    while (j < fileName.Length && (j - i) < s_maxReplace)
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs]: >fileName [](start = 31, length = 8)

length.

File: ReactWindows/ReactNative.Tests/Modules/Storage/AsyncStorageModuleTests.cs [hunk 2]
```diff
@@ -41,6 +41,55 @@ public void AsyncStorageModule_InvalidKeyValue_Method()
             Assert.AreEqual(error["message"], "Invalid Value");
             Assert.IsNull(result);
         }
+       
+        [TestMethod]
+        public void AsyncStorageModule_GetAllKeys_Valid()
```
Comment (rozele) [inline ReactWindows/ReactNative.Tests/Modules/Storage/AsyncStorageModuleTests.cs]: >AsyncStorageModule_GetAllKeys_Valid [](start = 20, length = 35)

Better name.

File: ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs [hunk 3]
```diff
@@ -327,78 +348,121 @@ public void OnDestroy()
...
 
             return null;
         }
 
         private async Task<JObject> SetAsync(string key, string value)
         {
-            var localFolder = ApplicationData.Current.LocalFolder;
-            var file = await localFolder.CreateFileAsync(GetFileName(key), CreationCollisionOption.ReplaceExisting).AsTask().ConfigureAwait(false);
+            var storageFolder = await GetAsyncStorageFolder(true);
+            var file = await storageFolder.CreateFileAsync(GetFileName(key), CreationCollisionOption.ReplaceExisting).AsTask().ConfigureAwait(false);
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs]: ConfigureAwait.

**Comment by rozele** [comment]
>                 }

Use cached folder (but set to null).

---
Refers to: ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs:260 in f292f41. [](commit_id = f292f41bc649953757b389ab040fa61f99dada98, deletion_comment = False)

File: ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs [hunk 4]
```diff
@@ -327,78 +348,121 @@ public void OnDestroy()
...
             await FileIO.WriteTextAsync(file, value).AsTask().ConfigureAwait(false);
             return default(JObject);
         }
 
+        private async Task<StorageFolder> GetAsyncStorageFolder(bool createIfNotExists)
+        {
+            if (s_cachedFolder == null)
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Storage/AsyncStorageModule.cs]: >s_cachedFolder [](start = 16, length = 14)

not s_ anymore.
