### PR TITLE
fix(ReactInstance): Set bridge instance before calling LoadScript

### LINKED ISSUE #744: Native exception when JS calls a native method during initial script run
When JS calls a native method too early during app initialization, I'm seeing an exception on this line because `_bridge` is `null`: https://github.com/ReactWindows/react-native-windows/blob/788061fde25648880a472f1c1f3f7cd1791f535b/ReactWindows/ReactNative/Bridge/ReactInstance.cs#L142

I believe this is the line that is running the JS: https://github.com/ReactWindows/react-native-windows/blob/788061fde25648880a472f1c1f3f7cd1791f535b/ReactWindows/ReactNative/Bridge/ReactInstance.cs#L117

Notice that `_bridge` hasn't been assigned at that point.

I suspect you can repro this bug by calling a native method at the toplevel of `index.window.js`.

### PR DESCRIPTION
**Pull request by rozele**
JavaScript may call native behaviors prior to the `_bridge` variable being set in `ReactInstance`, which would be invoked in the initial call to `FlushedQueue` following the call to run the bundle.

This change set ensures the `_bridge` is set before the bundle is loaded.

Fixes #744

### CODE REVIEW

File: ReactWindows/ReactNative/Bridge/ReactInstance.cs [hunk 1]
```diff
@@ -109,15 +109,19 @@ public void Initialize()
...
+                        _bridge.SetGlobalVariable("__fbBatchedBridgeConfig", BuildModulesConfig());
                     }
 
-                    _bundleLoader.LoadScript(bridge);
-
-                    return bridge;
-                }).ConfigureAwait(false);
+                    _bundleLoader.LoadScript(_bridge);
+                    return default(object);
+                });
```
Comment (rozele) [inline ReactWindows/ReactNative/Bridge/ReactInstance.cs]: ConfigureAwait(false)
