### PR TITLE
fix(Symbolicate): Ensures symbolicate feature is working properly

### LINKED ISSUE #433: Symbolicate feature broken
The request for source code maps seem to crash the app.

### PR DESCRIPTION
**Pull request by rozele**
In order for the server-side symbolicate feature to work, Chakra needs to report the correct source filename.  Threading through the SourceUrl to the RunScript function to ensure this is correct for exceptions.

Fixes #433

### CODE REVIEW

File: ReactWindows/ReactNative/Bridge/ReactBridge.cs [hunk 1]
```diff
@@ -98,12 +98,13 @@ public void SetGlobalVariable(string propertyName, string jsonEncodedArgument)
         /// Evaluates JavaScript.
         /// </summary>
         /// <param name="script">The script.</param>
-        public void RunScript(string script)
+        /// <param name="sourceUrl">The source URL.</param>
+        public void RunScript(string script, string sourceUrl)
```
Comment (mpodwysocki) [inline ReactWindows/ReactNative/Bridge/ReactBridge.cs]: Should we also validate the sourceUrl?

**Comment by mpodwysocki** [comment]
Other than the one comment, LGTM 💯
