### PR TITLE
fix(DevSupport): terminate live reload poller immediately when disabled.

### LINKED ISSUE #600: Eagerly bail out of file change poller
The dev server poller will delay one final time after cancellation. We can catch the cancellation operation and terminate immediately.

### PR DESCRIPTION
**Pull request by rozele**
Fixes #600

### CODE REVIEW

**Comment by mpodwysocki** [comment]
LGTM

File: ReactWindows/ReactNative/DevSupport/DevServerHelper.cs [hunk 1]
```diff
@@ -188,7 +188,11 @@ public IDisposable StartPollingOnChangeEndpoint(Action onServerContentChanged)
                             }
                         }
                     }
-                    catch
+                    catch (OperationCanceledException)
+                    when (disposable.IsDisposed)
+                    {
+                    }
+                    catch (Exception)
```
Comment (rozele) [inline ReactWindows/ReactNative/DevSupport/DevServerHelper.cs]: (Exception) not needed.
