### PR TITLE
fix(FrameDispatch): All operations on Rendering event should catch exceptions

### LINKED ISSUE #750: App can get into state where it is stuck crashing on launch
If you write some JavaScript code that causes a native exception during startup, the app can get stuck in this state. Each time you launch the app, it crashes. Even after fixing the JavaScript code, the app still crashes because the old JavaScript code appears to still be used. It crashes so soon that there's no opportunity to hit "ctrl+r" to get it to download the new JavaScript bundle.

Here's an example render function which causes a native exception which terminates the app:

```
  render() {
    return (
      <View style={styles.container}>
        <Text>
          <View style={{backgroundColor: 'red'}}>
            <Text>Crash</Text>
          </View>
        </Text>
      </View>
    );
  }
}
```

As a workaround, I commented out [this line](https://github.com/ReactWindows/react-native-windows/blob/6ae4661404c2ba83cdbfe7380b2f37b82643c7f5/ReactWindows/ReactNative/UIManager/UIViewOperationQueue.cs#L471) so that the app would render nothing, not crash, and give me the opportunity to hit "ctrl+r" to download the latest bundle.

The reason this render function doesn't work is a known issue (#685).

### PR DESCRIPTION
**Pull request by rozele**
Previously, failures on the CompositionTarget.Rendering event could crash the app. With these changes, each frame callback has an exception handling wrapper.

Fixes #750

### CODE REVIEW

File: ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs [hunk 1]
```diff
@@ -243,6 +243,18 @@ private long GetEventCookie(int viewTag, short eventTypeId, short coalescingKey)
                 (((long)coalescingKey) & 0xffff) << 48;
         }
 
+        private void ScheduleDispatcherSafe(object sender, object e)
```
Comment (rozele) [inline ReactWindows/ReactNative/UIManager/Events/EventDispatcher.cs]: Use this to subscribe to the event.
