### PR TITLE
fix(Image): Catch Uri loading exceptions for Images

### LINKED ISSUE #665: An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll but was not handled in user code
Running an app containing a network image but running with no internet connectivity causes an app to crash. 

Running the app via Visual Studio give this error 

```
An exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.ni.dll but was not handled in user code
```

It seems line 136 in `ReactWindows\ReactNative\Modules\Image\RefCountImageCache.cs` is requesting the image but not handling the exception.

### PR DESCRIPTION
**Pull request by rozele**
FileNotFoundException was not being caught, causing app crashes when URIs for images did not exist.

Fixes #665

### CODE REVIEW

File: ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs [hunk 1]
```diff
@@ -1,11 +1,15 @@
...
 using System;
 using System.Collections.Generic;
+using System.IO;
 using System.Reactive;
+using System.Reactive.Concurrency;
 using System.Reactive.Disposables;
 using System.Reactive.Linq;
 using System.Reactive.Subjects;
 using System.Threading;
+using System.Threading.Tasks;
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs]: Don't think this is being used.

File: ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs [hunk 2]
```diff
@@ -127,26 +129,34 @@ private void DoSubscribe(BitmapImage image)
                     });
 
                 _subscription.Disposable = openedObservable
-                    .Merge(failedObservable)
+                    .Merge(failedObservable, Scheduler.Default)
```
Comment (rozele) [inline ReactWindows/ReactNative/Modules/Image/RefCountImageCache.cs]: Get rid of this for now.

File: ReactWindows/ReactNative/Views/Image/ReactImageManager.cs [hunk 3]
```diff
@@ -299,13 +299,15 @@ private void SetUriFromSingleSource(Border view, string source)
...
             var reference = _imageCache.Get(source);
-            var subscription = reference.LoadedObservable.Subscribe(
-                _ =>
-                {
-                    imageBrush.ImageSource = reference.Image;
-                    OnImageOpened(view);
-                },
-                _ => OnImageFailed(view));
+            var subscription = reference.LoadedObservable
+                .ObserveOnDispatcher()
```
Comment (rozele) [inline ReactWindows/ReactNative/Views/Image/ReactImageManager.cs]: Delete.
