### PR TITLE
fix(TextInput): Fixes race between counter increment and JavaScript props changes

### LINKED ISSUE #490: Fix cursor race condition in TextInput
When holding the back space, it seems the cursor can get ahead of the TextInput state.

E.g., you could end up with...

aaaaaaaaaaaaaaaaaaaaaaaaaa|
aaaaaaa|aa

when the native state gets out of sync with the JavaScript state.

### PR DESCRIPTION
**Pull request by rozele**
Previously, the native event count was not updated until the TextChanged event fired, which could be interrupted by a previous props update. When this occurred, we could potentially replace the text with the state of a previous event.

Now, the native event count is pre-incremented in th TextChanging event. This seems to resolve the race condition.

Fixes #490

### CODE REVIEW

File: ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs [hunk 1]
```diff
@@ -405,33 +405,38 @@ public override void UpdateExtraData(ReactTextBox view, object extraData)
...
                     view.SelectionChanged -= OnSelectionChanged;
                 }
 
+                var text = textUpdate.Item2;
                 var selectionStart = view.SelectionStart;
                 var selectionLength = view.SelectionLength;
                 var textLength = text?.Length ?? 0;
                 var maxLength = textLength - selectionLength;
 
+                var currText = view.Text;
```
Comment (mpodwysocki) [inline ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs]: Where is `currText` being used?

**Comment by mpodwysocki** [comment]
Other than that one nit, LGTM

File: ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs (hunk 1 above)
Comment (rozele) [inline ReactWindows/ReactNative/Views/TextInput/ReactTextInputManager.cs]: Ugh, was for debugging.
